if(NOT GCC_ARM_LIST_TO_STRING_INCLUDED)

include(GCCARMDebugOutput)

function(ListToString output)
	set(_newOutput)
	foreach(i RANGE 1 ${ARGC})
		if(NOT ${ARGV${i}})
			if("${ARGV${i}}" MATCHES ";")
				DebugOutput("ListToString: Found list at ${i} '${ARGV${i}}'.")
				foreach(j in ${ARGV${i}})
					DebugOutput("ListToString: Adding item '${ARGV${i}}'.")
					set(_newOutput "${_newOutput} \"${j}\"")
				endforeach()
				
				#ListToString(_temp ${ARGV${i}})
				#Debugoutput("ListToString: Adding list string '${_temp}'.")
				#set(_newOutput "${_newOutput} ${_temp}")
			else()
				DebugOutput("ListToString: Adding item '${ARGV${i}}'.")
				set(_newOutput "${_newOutput} \"${ARGV${i}}\"")
			endif()
		endif()
	endforeach()
	
	DebugOutput("ListToString: Returning string to '${output}' '${_newOutput}'.")
	string(STRIP "${_newOutput}" _newOutput)
	set(${output} "${_newOutput}" PARENT_SCOPE)
endfunction()

set(GCC_ARM_LIST_TO_STRING_INCLUDED 1)
endif()
